from app.api.routes import (
    health,
    dramas,
    ai_configs,
    images,
    videos,
    tasks,
    character_library,
    upload,
    scenes,
    storyboards,
    video_merges,
    audio,
    assets,
    settings,
    script_generation,
)

__all__ = [
    "health",
    "dramas",
    "ai_configs",
    "images",
    "videos",
    "tasks",
    "character_library",
    "upload",
    "scenes",
    "storyboards",
    "video_merges",
    "audio",
    "assets",
    "settings",
    "script_generation",
]
